// Package claude provides the concrete implementation for distribution targeting Claude Code.
//
// This package implements the four interfaces source.Builder and
// inventory.Installer / Uninstaller / Lister, and confines all knowledge
// specific to Target = "claude" (directory conventions, frontmatter
// conventions, rule concatenation, and label persistence) to this package.
//
// # Target
//
// The target handled by this package is exposed as [Target]
// (a source.Target constant corresponding to the kebab-case string "claude").
// The Builder / Installer / Uninstaller / Lister implementations are each
// dedicated to a single target, and their Target() methods return this constant.
//
// # Directory Conventions (Inventory)
//
// Following Claude Code conventions, Installations are placed as follows.
// The Inventory root changes by Scope:
//
//   - ScopeUser:    $HOME/.claude/
//   - ScopeProject: <project root>/.claude/
//
// The structure under the root is the same regardless of Scope:
//
//   - skills/<name>/SKILL.md   ← Kind: skill
//   - agents/<name>.md         ← Kind: agent
//   - commands/<name>.md       <- Kind: prompt
//   - CLAUDE.md                <- Kind: rule (multiple rule entries concatenated with headings)
//
// # Artifact.Path Convention
//
// source.Artifact.Path generated by Builder is a path relative to the Inventory
// root above (for example, "skills/orchestrator/SKILL.md",
// "agents/solid-reviewer.md", "CLAUDE.md", "commands/review.md").
// This convention lets Builder generate paths without depending on Scope, while
// Installer / Uninstaller / Lister can confine (Scope, root) -> absolute-path
// resolution to one place.
//
// # Frontmatter Conventions
//
// SKILL.md and agent .md files have YAML frontmatter. Builder assembles
// generated frontmatter using the following rules:
//
//  1. Neutral fields (name, description, uses_skills, etc.) are transformed to
//     match Claude Code conventions and written to generated frontmatter.
//     For agents, uses_skills (a neutral ID array) is expanded into Claude
//     Code's "skills:", and each element is converted by extracting only the
//     <entry-name> portion from <pack>.skill.<entry> (per knowledge-format.md).
//  2. Keys / values from Entry.Tools["claude"].Frontmatter are merged with
//     overwrite semantics (Frontmatter values win for duplicate keys).
//
// CLAUDE.md has no frontmatter. It consists only of a Markdown body and is
// concatenated in manifest order, adding the pack name as an H1 heading and
// each rule entry name as an H2 heading.
//
// commands/<name>.md (prompt) is currently generated as pure Markdown body
// without frontmatter (the implementation still keeps frontmatter merge
// machinery for future extensibility).
//
// # Label Persistence Strategy
//
// Labels are not embedded in artifact files themselves; instead they are
// managed in a dedicated knit metadata directory selected by the CLI layer:
//
//   - ScopeUser:    $HOME/.knit/labels/<target>/<scope>/<installation id>.json
//   - ScopeProject: <project root>/.knit/labels/<target>/<scope>/<installation id>.json
//
// Each sidecar file stores minimal metadata such as Label, Provenance, and the
// corresponding relative path in Inventory.
// Claude Code does not inspect the knit metadata tree, so this coexists
// cleanly with Claude Code's existing conventions.
//
// Reasons for adopting the sidecar approach:
//
//   - xattr works on both macOS and Linux, but is fragile on NFS / FAT and can
//     interfere with users' dotfiles synchronization.
//   - Keeping knit-managed metadata under $HOME/.knit / <project>/.knit avoids
//     writing bookkeeping files into tool-owned directories such as ~/.claude.
//   - Storing the relative artifact path in the sidecar preserves enough
//     information to detect and ignore orphan labels when artifacts are removed
//     externally.
//
// # Scope Handling
//
// The project root that serves as the base for "<project>/.claude" used by
// ScopeProject is passed in via constructor arguments (this package does not
// discover project roots itself). That decision belongs to the CLI layer.
package claude
