// Package gemini provides the concrete implementation for Gemini CLI distribution.
//
// This package implements the four interfaces source.Builder and
// inventory.Installer / Uninstaller / Lister, and confines all knowledge
// specific to Target = "gemini" (directory conventions, file formats,
// frontmatter conventions, rule concatenation, and Label persistence) to this
// single package.
//
// For the normative specification, see [docs/gemini-target.md]. This doc.go
// extracts only the points required to understand the implementation
// signatures.
//
// # Target
//
// The Target handled by this package is exposed as [Target] (the source.Target
// constant corresponding to the kebab-case string "gemini"). Every Builder /
// Installer / Uninstaller / Lister implementation is dedicated to this single
// Target, and its Target() method returns this constant.
//
// # Directory Layout (Inventory)
//
// Following Gemini CLI conventions, Installations are placed as follows.
// The Inventory root switches by Scope:
//
//   - ScopeUser:    $HOME/.gemini/
//   - ScopeProject: <project root>/.gemini/
//
// The structure under root is the same for every Scope:
//
//   - skills/<name>/SKILL.md   <- Kind: skill
//   - agents/<name>.md         <- Kind: agent
//   - commands/<name>.toml     <- Kind: prompt (TOML format)
//   - GEMINI.md                <- Kind: rule (multiple rule entries concatenated with headings)
//
// # Artifact.Path Convention
//
// source.Artifact.Path generated by Builder is a relative path from the
// Inventory root above (for example: "skills/orchestrator/SKILL.md",
// "agents/solid-reviewer.md", "GEMINI.md", "commands/review.toml").
// This convention lets Builder generate Paths without depending on Scope, and
// centralizes (Scope, root) -> absolute path resolution in Installer /
// Uninstaller / Lister.
//
// # File Formats and Frontmatter Conventions
//
// A defining trait of this target is that the generated file format differs by
// kind.
//
//   - skill (SKILL.md): YAML frontmatter + Markdown body.
//     Following Gemini CLI conventions, the frontmatter emits only "name" and
//     "description". Other neutral fields (tags, uses_skills, etc.) are not
//     reflected. Keys / values in Entry.Tools["gemini"].Frontmatter are merged
//     with same-name keys taking precedence.
//
//   - agent (agents/<name>.md): YAML frontmatter + Markdown body (the body is
//     the System Prompt).
//     The frontmatter emits "name" and "description" from neutral fields.
//     The neutral field uses_skills is not reflected in this release because
//     the Gemini CLI subagent format has no direct slot for it; see
//     gemini-target.md "Undecided / Temporary Handling" for details.
//     Other Gemini CLI-specific fields (kind / tools / mcpServers / model /
//     temperature / max_turns / timeout_mins) are overridden through
//     Entry.Tools["gemini"].Frontmatter.
//
//   - rule (GEMINI.md): Markdown only, with no frontmatter
//     (Gemini CLI does not interpret frontmatter in GEMINI.md).
//     The pack name is emitted as H1 and each rule entry name as H2, in
//     manifest order. If Entry.Tools["gemini"].Frontmatter is non-empty,
//     ErrFrontmatterMergeConflict is returned because the structure cannot
//     represent it.
//
//   - prompt (commands/<name>.toml): generated in **TOML format** (not
//     Markdown).
//     Following the Gemini CLI Custom Commands spec, the required key "prompt"
//     receives the neutral Body and the optional key "description" receives
//     the neutral description. Keys / values in
//     Entry.Tools["gemini"].Frontmatter are override-merged as TOML top-level
//     keys, with Frontmatter taking precedence on conflicts. For the type
//     mapping used when emitting Go values originating from YAML into TOML
//     values, see builder.go "TOML encoding rules for
//     Tools[\"gemini\"].Frontmatter".
//
// The neutral Body is embedded byte-exact as-is. knit does not insert Gemini
// CLI-specific placeholders (`{{args}}`, `!{...}`, `@{...}`).
//
// # Internal Design Aggregation Points
//
// The resolution rules for "(Scope, Artifact.Path) -> absolute path" and
// "(Scope) -> Inventory root" are centralized by buildResolver in
// path_policy.go, which constructs the target-neutral inventory.PathResolver
// used by Installer / Uninstaller / Lister.
//
// # Label Persistence
//
// Labels are not embedded in the artifact file itself. They are managed in a
// dedicated knit metadata directory selected by the CLI layer:
//
//   - ScopeUser:    $HOME/.knit/labels/<target>/<scope>/<installation id>.json
//   - ScopeProject: <project root>/.knit/labels/<target>/<scope>/<installation id>.json
//
// Each sidecar file stores Label, Provenance, and the minimum metadata needed,
// such as the corresponding relative path in the Inventory.
// Gemini CLI does not consult knit's metadata tree, so this coexists fully with
// existing Gemini CLI conventions.
//
// Reasons for choosing the sidecar approach, shared with the claude target:
//
//   - xattr works on both macOS and Linux, but is brittle on NFS / FAT and may
//     interfere with the user's dotfiles synchronization.
//   - Keeping knit-managed metadata under $HOME/.knit / <project>/.knit avoids
//     writing bookkeeping files into tool-owned directories such as ~/.gemini.
//   - Storing the relative artifact path in the sidecar preserves enough
//     information to detect and ignore orphan labels when artifacts are removed
//     externally.
//
// # Scope Handling
//
// The roots for ScopeUser (`"$HOME/.gemini"`) and ScopeProject
// (`"<project>/.gemini"`) are both provided as constructor arguments. This
// package does not auto-discover the HOME environment variable or the project
// root; that decision belongs to the cli layer.
// If projectRoot is the empty string, operations involving ScopeProject return
// ErrProjectRootNotConfigured.
package gemini
